### PR TITLE
Build matrix to speed up CI build process

### LINKED ISSUE #9946: How to speed up Grails test suite (currently running ~31 minutes)
I took a short look at the Travis tests, and learned that one test run usually take more than half an hour.

Take this example from one of the most recent builds https://travis-ci.org/grails/grails-core/builds/131420509

Here are a few observations:

* a script `./travis-build.sh` runs a series of commands sequentially
* only java version `1.7.0_76` is tested

the test jobs are
```
./gradlew --stacktrace test -x grails-test-suite-web:test
./gradlew --stacktrace grails-test-suite-web:test
./gradlew --stacktrace --info integrationTest
```
In other words (if I am not mistaken):

1. First run all tests (but exclude grails-test-suite-web:test)
2. Then run grails-test-suite-web:test separately
3. Finally run the integrationTest phase

Between each job, the gradle daemon is stopped, which also takes time to start it up again.

I have some questions: 

* Which errors (false positives) were introduced since the gradle daemon had to be stopped?
* Why is it necessary to run ` grails-test-suite-web:test` separately?
* Is there a way to run tests in parallel (if they run in a matrix for instance like the Angular tests do it)

My first thought was to suggest splitting the tests to run them in parallel, but the build script ends by pushing artifacts. According to a discussion https://github.com/travis-ci/travis-ci/issues/1548, a deployment activity _could_ be run after all matrix jobs have run successfully. (or at least, there is a workaround for it).

There are probably also other, time consuming parts of the script, but since the output is 3455 lines, there are probably a lot of things I cannot see right now.

Comments? 

PS. Feel free to split or reference this issue from actual pull requests. I would love to see some working code examples 👍

### PR DESCRIPTION
**Pull request by jesperronn**
This change re-wires how we use Travis for builds and changes it from running
tests suites sequentially to a more parallel form. (currently for the three
predefined test suites):

Details:
- Matrix build: Travis will run 3 builds concurrently on three different instances.
  This will ensure the last test suite will start immediately and not wait for
  normal test suite to start.
  For discussion see https://github.com/grails/grails-core/issues/9946
- Added `travis_after_all` script in order to defer publishing until all jobs
  finish.
  I took the script from grails GORM project: https://github.com/grails/grails-data-mapping/blob/bd72797a945e2f1a35d903a3ba676e36bd8074b3/.travis.yml
    (for now not using the latest version of travis_after_all.py)
- Build file refactoring: GIT configurations put in the same place
- Build file refactoring: Removed some duplicate git configurations as well
- Build file refactoring: Reordered scripts in .travis.yml to make it easier to
  see relations

Note that this should speed up the build by running 3 test suites in parallel
and therefore it should fix #9946

### CODE REVIEW

**Comment by jesperronn** [comment]
@jeffbrown I decided to make this PR against master, since @graemerocher recently committed a master-only change to the central `travis-build.sh` (commit a00af2dead8d780a7ffc1ef3483f1eefc9448bf2).

Since this will speed up the CI process and give faster feedback, there is a fair reason to backport it.

I suggest you merge this onto master (in case you want the change).

Following that, we can discuss how to backport changes like this and a00af2dead8d780a7ffc1ef3483f1eefc9448bf2 onto the 3.1.x and 3.0.x branches

**Comment by jesperronn** [comment]
Woot! Down from approx 30minutes to 14!!!

> Elapsed time 13 min 56 sec

https://travis-ci.org/grails/grails-core/builds/135854607

**Comment by jesperronn** [comment]
Awesome @graemerocher  thanks for reviewing and merging!

**Comment by graemerocher** [comment]
Thanks for the contribution

**Comment by jesperronn** [comment]
I hope these changes make sense, and I think there is even more to do. One example is the usage of `exit`, which Travis advises not to use. Also it seems like there is a lot of slow publishing and dependent building going on. Let's leave that for other tasks later. 

Finally, if you want me to port to 3.0.x or 3.1.x, then by all means tag me, I will happily assist :)

**Comment by graemerocher** [comment]
happy for you to port these changes to 3.0.x/3.1.x if you want.. the more contributions the merrier :)

**Pull request merged**
