### PR TITLE
Add the @EnableScheduling to the Application class

### LINKED ISSUE #11320: @Scheduled stopped working in Grails 4
### Steps to Reproduce

1. Create a new app with grails 4.0.0.RC1
2. Add a service with a method annotated with `@Scheduled(fixedDelay = 10000L)`
3. Run the app

### Expected Behaviour

Method created should be executed every 10 seconds

### Actual Behaviour

Method is never executed

### Environment Information

- **Operating System**: Ubuntu 18.04
- **Grails Version:** 4.0.0.RC1
- **JDK Version:** Tested in 8.0.202 and 11.0.3

### PR DESCRIPTION
**Pull request by niravassar**
fixes https://github.com/grails/grails-core/issues/11320

### CODE REVIEW

**Comment by niravassar** [comment]
> @EnableScheduling

The reason i created this PR is because in Grails 3 the annotation was not required to be used to have scheduling with spring. I am not sure of the reason why, but in Grails 4 it is needed. See this sample Grails 3 app.

https://github.com/niravassar/grails-scheduled-three

**Comment by jameskleeh** [comment]
I know I originally advocated for this change, but I think I agree with Graeme. This will impose some sort of performance penalty for folks who are not using the spring scheduling and it is very easily added for those that are.

**Comment by niravassar** [comment]
I think then we should update the guide for grails 4.0 then with a snippet that says @EnableScheduling needs to be added. I think I may have already done that. I will do that - bc in grails three it is not necessary but in grails 4 it is.

**Comment by jameskleeh** [comment]
@niravassar I've already done that

**Pull request closed without merging**
