### PR TITLE
Use gradle wrapper instead of default installed by Sdkman

### PR DESCRIPTION
**Pull request by ilopmar**
Fix for #10907 to use the Gradle wrapper provided by Grails instead of the default one installed by Sdkman.

### CODE REVIEW

**Comment by jameskleeh** [comment]
The code being removed was added because of https://github.com/grails/grails-core/issues/10207.

I think a middle of the road solution is to look for the specific version of gradle in the sdkman folder. If that doesn't exist, then use the wrapper.

**Comment by jeffbrown** [comment]
Can this solution be tied to `GRADLE_HOME` instead of having any kind of hardcoded reference that have anything to do with SdkMan?

**Comment by jeffbrown** [comment]
Also, I think using `$userHome/.sdkman/candidates/gradle/current` is problematic because `current` isn't always the one being used.  When do something like `sdk use gradle 4.1`, that doesn't move `current`...

```
~ $ which gradle
/Users/jeffbrown/.sdkman/candidates/gradle/current/bin/gradle
~ $ 
~ $ ls -l ~/.sdkman/candidates/gradle/current
lrwxr-xr-x  1 jeffbrown  staff  46 Oct  5 14:41 /Users/jeffbrown/.sdkman/candidates/gradle/current -> /Users/jeffbrown/.sdkman/candidates/gradle/3.5
~ $ 
~ $ sdk use gradle 4.1

Using gradle version 4.1 in this shell.
~ $ 
~ $ which gradle
/Users/jeffbrown/.sdkman/candidates/gradle/4.1/bin/gradle
~ $ 
~ $ ls -l ~/.sdkman/candidates/gradle/current
lrwxr-xr-x  1 jeffbrown  staff  46 Oct  5 14:41 /Users/jeffbrown/.sdkman/candidates/gradle/current -> /Users/jeffbrown/.sdkman/candidates/gradle/3.5
```

**Comment by jameskleeh** [comment]
I'm advocating for determining the gradle version and looking for a folder in sdkman. For example:

`~/.sdkman/candidates/gradle/${gradleVersion}/bin/gradle`

I agree the use of the `current` folder is problematic

**Comment by ilopmar** [comment]
I have a question. Do we really want to use a specific Gradle version instead of the current wrapper version?

**Comment by jeffbrown** [comment]
> I am advocating for determining the gradle version and looking for a folder in sdkman.

Is there a reason that is better than looking at `GRADLE_HOME`?

It seems like the surrounding issues don't have anything to do with SdkMan but instead are related to versions of Gradle that are on the `PATH`.  I wouldn't advocate for actually parsing the `PATH` but it seems like looking at `GRADLE_HOME` would be better than looking for SdkMan (or any other package manager) specific stuff.

**Comment by jameskleeh** [comment]
@ilopmar When I say determining the gradle version, I mean the version of the wrapper. I don't think we should use a version of Gradle that is different from the wrapper.

@jeffbrown The reason looking in the sdkman folder might be better is because GRADLE_HOME can point to a version of Gradle that is not compatible with the project.

**Comment by ilopmar** [comment]
> Is there a reason that is better than looking at `GRADLE_HOME`?

The issue is that `$GRADLE_HOME` can point to an old version. In my case:

```
$ echo $GRADLE_HOME
/home/ivan/.sdkman/candidates/gradle/current

$ ls -l /home/ivan/.sdkman/candidates/gradle/current
lrwxrwxrwx 1 ivan ivan 40 Jan 22 15:23 /home/ivan/.sdkman/candidates/gradle/current -> /home/ivan/.sdkman/candidates/gradle/2.14
```

This old 2.14 Gradle version reproduces the issue. If we use the same gradle wrapper we make sure that it will work because we control that version.

**Comment by ilopmar** [comment]
@jameskleeh So, as we are now using Gradle 3.5, you mean:

- Use `~/.sdkman/candidates/gradle/3.5/bin/gradle` is it exists
- If not, use the gradle wrapper in the grails directory?

**Comment by jameskleeh** [comment]
@ilopmar Yes that is what I'm proposing. The version should be able to be detected instead of hardcoded.

**Comment by ilopmar** [comment]
I can try that, but I've been trying to reproduce #10207 with my current code and I'm not able to do it. So I'm not really sure what will be the difference...

**Comment by jameskleeh** [comment]
@ilopmar The difference will be that if you haven't downloaded the version of Gradle via the wrapper, it won't download it if the version exists in sdkman. It will use the local installed version which doesn't require anything to download to use.

**Comment by ilopmar** [comment]
@jameskleeh sorry, I didn't explained correctly. I've removed my `~/.gradle/wrapper` and `~/.sdkman/candidates/gradle` directories and grails tries to use Gradle 3.0

```
$ grails run-app --stacktrace
| Running application...
FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/demo/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'demo'.
> Failed to apply plugin [id 'com.energizedwork.webdriver-binaries']
   > No signature of method: java.lang.String.uncapitalize() is applicable for argument types: () values: []
     Possible solutions: capitalize()

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'demo'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:177)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:182)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:573)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:125)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
        at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:124)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:121)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
        at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:46)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:82)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:59)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:49)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.HintGCAfterBuild.execute(HintGCAfterBuild.java:44)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:240)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'com.energizedwork.webdriver-binaries']
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:155)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:44)
        at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
        at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
        at build_b3gw57kprryvuq0bwcgw5ijh3.run(/tmp/demo/build.gradle:22)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        ... 60 more
Caused by: groovy.lang.MissingMethodException: No signature of method: java.lang.String.uncapitalize() is applicable for argument types: () values: []
Possible solutions: capitalize()
        at com.energizedwork.gradle.webdriver.WebDriverBinariesPlugin.createConfigureDriverBinary(WebDriverBinariesPlugin.groovy:52)
        at com.energizedwork.gradle.webdriver.WebDriverBinariesPlugin.createConfigureChromeDriverBinary(WebDriverBinariesPlugin.groovy:43)
        at com.energizedwork.gradle.webdriver.WebDriverBinariesPlugin$createConfigureChromeDriverBinary.callCurrent(Unknown Source)
        at com.energizedwork.gradle.webdriver.WebDriverBinariesPlugin.apply(WebDriverBinariesPlugin.groovy:38)
        at com.energizedwork.gradle.webdriver.WebDriverBinariesPlugin.apply(WebDriverBinariesPlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
        at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:139)
        ... 70 more

| Error Failed to start server (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.util.concurrent.ExecutionException: org.gradle.tooling.BuildException: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-3.0-bin.zip'.
```

So, I'm not sure if my patch actually fix the issue. I've also noticed that I can remove my patch because, the existing code already was using the current directory: https://github.com/grails/grails-core/pull/10908/files#diff-275725404fd4529759db17207070d4caR49

Another question. There is a way to retrieve `${gradleVersion}` in `GradleUtil`?

**Comment by jameskleeh** [comment]
@ilopmar I don't think so. I think you'd have to parse `gradle.properties` and look for `gradleWrapperVersion`

**Comment by ilopmar** [comment]
Changed to follow @jameskleeh suggestion:
- If `$gradleVersion` exist on Sdkman, then use that installation
- If not, then use the wrapper installation

**Comment by ilopmar** [comment]
@jameskleeh Checked if `gradle.properties` exists and is readable. If not the wrapper is used.

**Comment by zyro23** [comment]
i doubt that checking `gradle.properties` will cover all cases where a wrapper is present. e.g. we declare the wrapper version with `wrapper.gradleVersion = "1.2.3"` in `build.gradle` (no `gradle.properties`).

**Comment by jameskleeh** [comment]
@zyro23 In that case then the wrapper will be used

**Pull request merged**
