### PR TITLE
#9560 fix for running war in tomcat 7

### PR DESCRIPTION
**Pull request by rvanderwerf**
This is a fix for issue #9560 which blocks running war files under tomcat 7.

### CODE REVIEW

**Comment by graemerocher** [comment]
yeah but this breaks other things, better to catch the exception and ignore

**Comment by rvanderwerf** [comment]
Graeme do you know what those other things it breaks are? Is it running war in tomcat 8?

**Comment by graemerocher** [comment]
no it broke running as a jar i.e. `java -jar foo.war`

**Comment by rvanderwerf** [comment]
gotcha. Thanks for the info!

**Comment by graemerocher** [comment]
Already fixed, so closing...

**Pull request closed without merging**
