### PR TITLE
Fix #10226

### LINKED ISSUE #10226: UrlMappingsUnitTestMixin does not check exception mappings
By default the UrlMappingsUnitTestMixin does not perform a check against the type of exception inside UrlMappings.groovy. We currently sub-class UrlMappingsUnitTestMixin to test this feature, but I'd like to document its absence here.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an entry in UrlMappings.groovy mapping different actions for the '500' location based on the exception thrown
2. Create unit test that uses the UrlMappingsTestMixin to test using assertForwardUrlMapping
3. Observe the test failure

### Expected Behaviour

assertForwardUrlMapping will test the exception mapping in UrlMappings.groovy

### Actual Behaviour

assertForwardUrlMapping only tests the action/controller, ignoring the exception.

### Environment Information

- **Operating System**: Ubuntu MATE 16.10
- **Grails Version:** 3.1.12
- **JDK Version:** OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)

### Example Application

https://github.com/joemccall86/url-mappings-mixin-test

### Other Notes

We have the workaround code already, and I'm putting together a PR to address this issue right now.

### PR DESCRIPTION
**Pull request by joemccall86**
Include the "exception" property when checking url mappings in UrlMappingsUnitTestMixin.

Fixes
https://github.com/grails/grails-core/issues/10226

### CODE REVIEW

**Comment by joemccall86** [comment]
Not sure if it takes a few minutes, but I did indeed sign the CLA.

**Comment by joemccall86** [comment]
Didn't mean to close the PR, just the comment box. :shrug:

**Comment by graemerocher** [comment]
If you want this to appear in 3.1.x and 3.2.x please submit to the 3.1.x branch

**Comment by joemccall86** [comment]
Thanks, I'll open a new PR pointed to that branch.

**Pull request closed without merging**
