### PR TITLE
Support the ad-hoc constraints for validate()

### PR DESCRIPTION
**Pull request by nobeans**
This makes the following code available.

```
person.validate {
    name maxSize: 10
    age max: 60
}
```

See https://github.com/grails/grails-core/issues/9599.

### CODE REVIEW

**Comment by zyro23** [comment]
would it make sense to add a boolean flag to decide if only the ad-hoc constraints should be validated or if they should be validated in addition to the existing constraints (which should be default)?

e.g. `myDomain.validate(onlyAdHocConstraintsNeedsBetterName: true) { ... }`

**Comment by graemerocher** [comment]
@zyro23 might be useful, I kind of like the sound of `onlyAdHocConstraintsNeedsBetterName` ;-)

**Comment by nobeans** [comment]
The default `nullable:true` (`defaultNullable()`) is unnecessary for the ad-hoc constraints when the option is `true`, isn't it?

And the candidates of signature are....

* `validate(only: true) { ... }`
* `validate(useDefault: true) { ... }`
* `validate(onlyAdHocConstraints: true) { ... }`
* `validate(ignorePreDeclaredConstraints: true) { ... }`
* `validateOnlyWith { ... }`
* `validate(inherit: false) { ... }` --> my favorite one
* `validate(extend: false) { ... }`
* `validate(cascade: false) { ... }`

**Comment by zyro23** [comment]
* `nullable: true` unnecessary: i think so. should behave exactly like standard validation?
* `inherit: false`: im fine with that (unless someone comes up with a better idea so the flag can default to `false` instead of `true`)

and one more thought: should existing errors be cleared or not when using this flag? i can imagine use-cases for both behaviors...

**Comment by graemerocher** [comment]
+1 for `inherit`

**Comment by nobeans** [comment]
@graemerocher and @zyro23 OK. The option is now `inherit: false`.

@zyro23
> nullable: true unnecessary: i think so. should behave exactly like standard validation?

Oh, I mistook. I meant that "`nullable:false` is unnecessary?" If a resolution of "Global Constraints" (`grails.gorm.default.constraints` in `applicaiton.groovy`) and default `nullable:false` are required, the difficulty is increased a little ;-)

> and one more thought: should existing errors be cleared or not when using this flag? i can imagine use-cases for both behaviors...

Seems nice. I think it's easer than the above. Is the option's name is...

* `resetErrors:true`
* `clearErrors:true`

**Comment by zyro23** [comment]
reg. global constraints and `nullable: false` as default when using `inherit: false`: even if it increases difficulty/effort (sry for that..), i guess same behavior as standard `validate()` makes most sense.

thinking a bit more about the error clearing, maybe no additional flag is needed:
* if `inherit: false` is used, errors should be added
    * you can still clear them manually with `Validateable.clearErrors()`
* else, errors should be cleared - behaving just like 2 successive calls to `validate()`

what do you think? @graemerocher your opinion is much appreciated as usual ofc :)

**Comment by nobeans** [comment]
To introduce `inherit:false`, we need to refactor and modify `DefaultConstraintEvaluater` and `Validateable`, etc. I'm trying to do it now.

If `inherit:false` isn't supported (it means providing only `inherit:true` mode), the work is unnecessary.

**Comment by nobeans** [comment]
@graemerocher

To support `clearErrors` and `inherit` option taking "default nullable", "default constraints (*)" and "shared constraints" into consideration, I needs to modify `DefaultConstraintEvaluator`. I wrote tests to understand current behaviors, then I found some differences between `Validateable` object and GORM's domain class.

* (1) Only GORM supports default constraints `*` (though both supports shared constraints)
* (2) Only `Validateable` considers a property which is implemented as only getter method to be constrainable.

They are issues or improvements to be fixed, aren't they? I've refactored `DefaultConstraintEvaluator` and fixed the above two issues. If they are issues, I'll create new issues at Github. Besides, I can sent the PR (as new or on this PR). Now I pushed my branch's code temporarily.


And one more thing, I've forgotten about GORM's support...

* (a) Only `Validateable` supports ad-hoc constraints so far.
* (b) Anyway, `Validateable` supports ad-hoc constraints so far, but GORM should be supported too ASAP.
* (c) `Validateable` can't be merged until GORM's support is available.

Which do you like better?

**Comment by nobeans** [comment]
At the current version, `Validateable#validate` supports the following call.

```
person.validate()
person.validate(clearErrors: true)
person.validate { age max: 18 }
person.validate { name maxSize: 99 } { age max: 18 } // multiple ad-hoc constraints supported
person.validate(clearErrors: true, inherit: false) { age max: 18 }
person.validate(clearErrors: true, inherit: false) { name maxSize: 99 } { age max: 18 }
person.validate(['age'])
person.validate(['age'], [clearErrors: true])
person.validate(['age']) { age max: 18 }
person.validate(['age']) { name maxSize: 99 } { age max: 18 }
person.validate(['age'], [clearErrors: true, inherit: false]) { age max: 18 }
person.validate(['age'], [clearErrors: true, inherit: false]) { name maxSize: 99 } { age max: 18 }
```

For further information, see https://github.com/nobeans/grails-core/blob/16ac66e27ddbb6e860564ef11e55e7911bd2979f/grails-test-suite-uber/src/test/groovy/grails/validation/ValidateableTraitAdHocSpec.groovy

**Comment by graemerocher** [comment]
Thanks I am away until next Thursday, will take a look then.

**Comment by graemerocher** [comment]
Thanks for the pull request, merged. Would be good to update documentation too

**Comment by nobeans** [comment]
Thanks. I'll try to update documentation later.

> And one more thing, I've forgotten GORM about ad-hoc constraints...
> 
> * (a) Only `Validateable` supports ad-hoc constraints so far.
> * (b) Anyway, `Validateable` supports ad-hoc constraints so far, but GORM should be supported too ASAP.
> * (c) `Validateable` can't be merged until GORM's support is available.
> 
> Which do you like better?

BTW, what do you think about GORM support?

**Comment by graemerocher** [comment]
GORM support would be good for consistency, that would require another pull request to g-d-m

**Comment by nobeans** [comment]
OK. Thanks.

**Comment by nobeans** [comment]
I added `DomainClassValidationSpec` based on `ValidateableTraitSpec` in order to ensure behaviors of domain class as contrasted with a command class implemented `Validateable`.

Currently, only `Validateable` supports to specify a default nullable value by a `defaultNullable` method implemented a target class.

However, in future, a domain class might support individual `defaultNullable` method and I want to keep the same kinds of test cases between `DomainClassValidationSpec` and `ValidateableTraitSpec` as possible. So I kept them with `@Ignored`.

**Comment by jeffbrown** [comment]
Possibly related to https://github.com/grails/grails-core/issues/9774.

**Pull request merged**
