### PR TITLE
Fix for #10387 - Date parsing should not be lenient and performance improvement

### PR DESCRIPTION
**Pull request by snimavat**
Fix for #10387

### CODE REVIEW

**Comment by jeffbrown** [comment]
This PR addresses separate issues.  One is the request related to `lenient`.  Another is this change results in `SimpleDateFormat` instances being kept around and re-used.  I think the way it is written, any particular formatter could be used by multiple concurrent requests, which would create problems I think.  Am I mistaken about that?

**Comment by snimavat** [comment]
you are right about synchronisation..

**Comment by jeffbrown** [comment]
> do you think we should synchronize ? or dont cache the fomatters at all ?

Synchronization isn't great because it means that concurrent requests that are doing date binding will have to wait in a queue.  For some scenarios that might be better than creating new ones over and over, but for some scenarios it will be worse.  I am open to suggestions.

One thing you can do to optimize for your own use cases is register your own `Date` `ValueConverter` that behaves in the way that  makes sense for your app.

Thanks for the feedback.

**Comment by jeffbrown** [comment]
One thing I would suggest is separating the `lenient` handling from the synchronization issue.  Those are separate and as it is right now, because they are in the same PR we can't accept the `lenient` improvement until the optimization thing is worked out, but they are separate issues.

**Comment by snimavat** [comment]
Would give a new pr just for lenient within next few hours

**Comment by jeffbrown** [comment]
@snimavat Great.  It may make sense to send the PR to the `3.1.x` branch.  We would merge it up the line from there.

Thanks for the feedback and thanks for the help.

**Pull request closed without merging**
