### PR TITLE
Use iteration instead of recursion to parse json array elements.

### PR DESCRIPTION
**Pull request by analbandyan**
#10757: The recursion in org.grails.web.json.parser.JSONParser#Elements was causing StackOverflowError when parsing long arrays. By this change recursion is replaced with iteration.

### CODE REVIEW

**Comment by analbandyan** [comment]
Note, Travis CI build failure does not seem to be related to my change.

**Comment by graemerocher** [comment]
Could this pull request include a test?

**Comment by analbandyan** [comment]
@graemerocher unit test added.

**Comment by jameskleeh** [comment]
@analbandyan Looks like the latest build failure might be due to these changes

**Comment by analbandyan** [comment]
@jameskleeh I didn't find anything related to my changes in build logs. This could be an intermediate (not code related) failure. How can I request a new build?

**Comment by ilopmar** [comment]
@analbandyan can you please create a new branch from `3.3.x` and only include your changes. You shouldn't use anything from `master`.

**Comment by analbandyan** [comment]
@ilopmar done, here is the new pull request: #10950

**Pull request closed without merging**
