### PR TITLE
Travis matrix build (speedup test suite)

### LINKED ISSUE #9946: How to speed up Grails test suite (currently running ~31 minutes)
I took a short look at the Travis tests, and learned that one test run usually take more than half an hour.

Take this example from one of the most recent builds https://travis-ci.org/grails/grails-core/builds/131420509

Here are a few observations:

* a script `./travis-build.sh` runs a series of commands sequentially
* only java version `1.7.0_76` is tested

the test jobs are
```
./gradlew --stacktrace test -x grails-test-suite-web:test
./gradlew --stacktrace grails-test-suite-web:test
./gradlew --stacktrace --info integrationTest
```
In other words (if I am not mistaken):

1. First run all tests (but exclude grails-test-suite-web:test)
2. Then run grails-test-suite-web:test separately
3. Finally run the integrationTest phase

Between each job, the gradle daemon is stopped, which also takes time to start it up again.

I have some questions: 

* Which errors (false positives) were introduced since the gradle daemon had to be stopped?
* Why is it necessary to run ` grails-test-suite-web:test` separately?
* Is there a way to run tests in parallel (if they run in a matrix for instance like the Angular tests do it)

My first thought was to suggest splitting the tests to run them in parallel, but the build script ends by pushing artifacts. According to a discussion https://github.com/travis-ci/travis-ci/issues/1548, a deployment activity _could_ be run after all matrix jobs have run successfully. (or at least, there is a workaround for it).

There are probably also other, time consuming parts of the script, but since the output is 3455 lines, there are probably a lot of things I cannot see right now.

Comments? 

PS. Feel free to split or reference this issue from actual pull requests. I would love to see some working code examples 👍

### PR DESCRIPTION
**Pull request by jesperronn**
Fixes #9946 

Matrix build: Travis will run 3 builds concurrently on three different instances.

This will ensure the last test suite will start immediately and not wait for normal test suite to start.

For discussion see https://github.com/grails/grails-core/issues/9946

NOTE that the best order is to merge the two other PRs ahead of this:
- https://github.com/grails/grails-core/pull/9952
- https://github.com/grails/grails-core/pull/9953

### CODE REVIEW

**Comment by graemerocher** [comment]
Doesn't the build leader need to wait until all of the child builds in the matrix have completed before publishing?

**Comment by jesperronn** [comment]
@graemerocher good point. I am not sure yet, and want to see how it behaves. My assumption right now is that Travis will figure it out automatically and only continue the `after_success` or `after_failure` and the `deploy` hooks when all matrix jobs are done.

When the job finishes, we can probably see more. 

If any changes are required, I probably will re-edit the commit and push another commit. (for the record, this comment refers to commit 864499a9c7aa0386a008bdee79c75201dc6bb886)

**Comment by jesperronn** [comment]
@graemerocher you were right about the assumption that the build leader has to wait. I see from [Job #2244.3](https://travis-ci.org/grails/grails-core/jobs/132200421) that it ends running

```
$ ./travis-publish-archives.sh
$ ./trigger-dependent-build.sh
```

The intention is that it should wait and only run those once all jobs are successfully finished.

Will update, but later :)

**Comment by jesperronn** [comment]
@graemerocher I added the `travis_after_all.py` script to the build, but it seems that it still continues and runs the other steps in `after_success`. 

Example https://travis-ci.org/grails/grails-core/builds/132210393 for Job [2246#3](https://travis-ci.org/grails/grails-core/jobs/132210395) 

Any suggestions?

**Comment by graemerocher** [comment]
@jesperronn I don't know, our other build for GORM uses this script and seems to work ok https://github.com/grails/grails-data-mapping

**Comment by jesperronn** [comment]
@graemerocher sorry, this actually works as intended. I was not reading the collapsed lines:

https://travis-ci.org/grails/grails-core/jobs/132218277#L543
```
$ ./travis-publish-archives.sh
Project Version: ''
EXIT STATUS of build: ''
Not build leader, exiting
```

So, other than that, the same check needs to go into the next script file (`./trigger-dependent-build.sh`)

**Comment by jesperronn** [comment]
@graemerocher I think it works now, and fixes #9946 

If you decide to merge, could you please merge in the order I created the 3 PRs? (see top)

**Comment by jesperronn** [comment]
Closing in favor of #9979

**Pull request closed without merging**
