### PR TITLE
GRAILS-12089 Fix auto timestamp properties not populated with @Mock

### PR DESCRIPTION
**Pull request by slaunay**
- initialize entities for AutoTimestampEventListener to detect and cache auto timestamps properties
- add unit test case to detect potential future regressions
- removing ControllerTestForTest (duplicating ControllerTestForTests)

### CODE REVIEW

**Comment by jspiewak** [comment]
Did this fix need to be carried forward into 2.5.x as well?

**Comment by jeffbrown** [comment]
@graemerocher Should this be merged to 2.5.x?

**Comment by graemerocher** [comment]
it should have been yes

**Comment by jeffbrown** [comment]
Ok.  I have now merged the change to 2.5.x.

@graemerocher @slaunay Was the deletion of `ControllerTestForTest` at https://github.com/grails/grails-core/commit/addc3d48247d59a174788bdf048fc2e255c92359 intentional?

**Comment by graemerocher** [comment]
can't recall, probably an accident...

**Comment by jeffbrown** [comment]
I see now there is a comment above which calls it out:

> removing ControllerTestForTest (duplicating ControllerTestForTests)

I had not noticed that before.

**Comment by graemerocher** [comment]
Ok I see, yes it was a duplicate, not sure why it was deleted as part of this commit, nevertheless...

**Comment by slaunay** [comment]
> Was the deletion of ControllerTestForTest at addc3d4 intentional?

Yes it was on purpose, I noticed that duplicated test and was lazy about creating a separate PR thinking it would not be an issue for merging upstream :disappointed:.

**Comment by jeffbrown** [comment]
@slaunay It wasn't really an issue.  Occasionally we get pull requests that have accidentally included changes that the author didn't realize they committed.  When I saw the unrelated test deletion I wondered if that was the case here.  After I commented I saw the description of why the test was deleted.

In general, don't lump unrelated stuff together because it can be problematic but in this case it wasn't a big deal.  Thank you very much for contributing.  Help is appreciated.

**Pull request merged**
