### PR TITLE
Fix for #10403 - Recognize properties with the second letter capitalized

### LINKED ISSUE #10403: ClassPropertyFetcher does not recognize properties that have their second letter capitalized
### Steps to Reproduce

1. Create a domain class like this:

```
class TestDomainClass {
  String cType

  static constraints = {
    cType nullable: true
  }
}

```
2. Try to save an instance of the class

### Expected Behaviour

The class should load and be usable

### Actual Behaviour

The validation code for the class throws an exception:

```
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:62)
	at org.grails.validation.ConstrainedPropertyBuilder.doInvokeMethod(ConstrainedPropertyBuilder.java:74)
	at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:67)
	at mypackage.TestDomainClass._clinit__closure1(TestDomainClass.groovy:7)
	at mypackage.TestDomainClass._clinit__closure1(TestDomainClass.groovy)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:408)
	at org.grails.validation.DefaultConstraintEvaluator.evaluateConstraintsMap(DefaultConstraintEvaluator.java:239)
	at org.grails.validation.DefaultConstraintEvaluator.evaluateConstraints(DefaultConstraintEvaluator.java:132)
	at org.grails.validation.DefaultConstraintEvaluator.evaluateConstraints(DefaultConstraintEvaluator.java:119)
	at org.grails.validation.DefaultConstraintEvaluator.evaluate(DefaultConstraintEvaluator.java:108)
	at org.grails.core.DefaultGrailsDomainClass.initializeConstraints(DefaultGrailsDomainClass.java:755)
	at org.grails.core.DefaultGrailsDomainClass.getConstrainedProperties(DefaultGrailsDomainClass.java:746)
	at org.grails.validation.GrailsDomainClassValidator.validate(GrailsDomainClassValidator.java:76)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:122)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:151)
	at mypackage.TestDomainClassSpec.$tt__$spock_feature_1_0(TestDomainClassSpec.groovy:15)
```
### Environment Information

- **Operating System**: Linux Ubuntu 16.10
- **Grails Version:** 3.2.3
- **JDK Version:** 1.8.0_91
- **Container Version (If Applicable):** n/a

### Problem analysis

in org.grails.core.util.ClassPropertyFetcher line 133 the code tries to figure out if a method is a property getter, and if so calculate the property name. The code only checks if the method name starts with "get" followed by a capital letter. This misses properties like `xAge` that start with a small letter followed by a capital, as such properties have getters of the form `getxAge()`.

### PR DESCRIPTION
**Pull request by JanKanis**
Make ClassPropertyFetcher also recognize properties of the form "xAge" that have the second letter capitalized.

Fixes #10403

Note: I included a test case, but I wasn't able to run that myself. I'm relying on Travis here.

### CODE REVIEW

**Comment by jeffbrown** [comment]
Does this impose the same rules as those imposed around the code affected by https://github.com/grails/grails-core/commit/87d644e1e46a357051c798a4e0caa0885668c618?

**Comment by JanKanis** [comment]
@jeffbrown Mostly yes, I missed the isaBool case. 

I wasn't aware that there was already similar logic in GrailsClassUtil. I added two commits to the PR, the first one to improve GrailsClassUtils.getPropertyForGetter to make sure it detects the same getters as GrailsClassUtils.isGetter and nothing more (and include test cases for all the edge cases). The second commit changes GrailsPropertyFetcher to make use of the logic in GrailsClassUtils.

The second commit has a small behavioral change: for a static getter `getProp` ClassPropertyFetcher would register two static properties: `Prop` and `prop`, in the new code it only registers `prop`. The old behavior looks like a workaround so that a static getter `getURL` would also register as property `URL` and not just `uRL`. But someone needs to check that.

**Comment by graemerocher** [comment]
If you would like this included in a future `3.1.x` or `3.2.x` release will need it against the equivalent branch.

**Comment by JanKanis** [comment]
@graemerocher Sure. What's your process here? a PR against `3.1.x` and then `3.1.x` is merged into `3.2.x` which is merged into `master`?

**Comment by JanKanis** [comment]
@graemerocher I made a copy of this PR in #10414 against the 3.1.x branch.

**Pull request closed without merging**
