### PR TITLE
Added method to retrieve the codes of a specific bundle.

### PR DESCRIPTION
**Pull request by tkvw**
For example if you want to send all client messages contained in
messagesclient bundle to the browser using i18next, you can now
retrieve all codes contained in the messagesclient bundle.

### CODE REVIEW

**Comment by graemerocher** [comment]
Please also provide tests

**Comment by tkvw** [comment]
Sorry for late response, was on a holiday, test added.

**Comment by tkvw** [comment]
Why is the travis build failing on my test? Can't I use the java.io.tmpdir? It runs on my development environment.

**Comment by graemerocher** [comment]
Good question, make try use File.createTempDir instead

**Comment by tkvw** [comment]
Same issue, could it be that you need to add a TMPDIR to the travis build config? 
```
env:
  global:
    - TMPDIR=/tmp
```

**Comment by tkvw** [comment]
Is there a way for me to retrieve the report file:///home/travis/build/grails/grails-core/grails-core/build/reports/tests/test/index.html of the travis build?

**Comment by tkvw** [comment]
Apparently travis doesn't allow the creation of temp files, switched to ByteArrayResource and now the test is building. It would be great if you can include this PR.

**Pull request merged**
