### PR TITLE
Fix GRAILS-11863 GRAILS-11864

### PR DESCRIPTION
**Pull request by demon101**
fixes for 
https://jira.grails.org/browse/GRAILS-11864
https://jira.grails.org/browse/GRAILS-11863

### CODE REVIEW

**Comment by jeffbrown** [comment]
Do you have any relevant unit tests?  Thanks for the help.

**Comment by demon101** [comment]
no, sorry

**Comment by jeffbrown** [comment]
The following tests in grails-test-suite-web start failing after these changes are applied...

* RegexUrlMappingTests.testNullableConstraintsInMapping
* ReverseUrlMappingTests.testLinkTagRendering
* LinkRenderingTagLibTests.testMappingsWhichSpecifyAPlugin
* LinkRenderingTagLibTests.testOverlappingReverseMappings
* LinkRenderingTagLibTests.testRenderLinkWithReverseMapping

**Comment by demon101** [comment]
How I can start tests? By 'gradle test' I got same results with https://travis-ci.org/grails/grails-core/builds/47338166
I will write tests tonight

**Comment by jeffbrown** [comment]
./gradlew :grails-test-suite-web:test

**Comment by demon101** [comment]
Fix has been fixed =) 
Sorry for mistake. The code is very confusing

**Comment by jeffbrown** [comment]
Will do another review soon.  Thanks again for the help.

**Comment by demon101** [comment]
any news?

**Comment by jeffbrown** [comment]
Does this resolve both GRAILS-11863 and GRAILS-11864?

**Comment by demon101** [comment]
Yes, for both.

**Comment by demon101** [comment]
when tasks will be marked as fixed?

**Pull request merged**
