### PR TITLE
GRAILS-11696 g:sortableColumn does not allow namespace for link creation

### PR DESCRIPTION
**Pull request by wololock**
This PR fixes an issue reported here on JIRA https://jira.grails.org/browse/GRAILS-11696

### CODE REVIEW

**Comment by orkonano** [comment]
@lhotari Do you know when this bug will be in production?

**Comment by wololock** [comment]
This fix will be shipped in 2.4.5 version, check [JIRA](https://jira.grails.org/browse/GRAILS-11696) issue report

**Comment by orkonano** [comment]
Thanks. Do you know the date?

**Comment by wololock** [comment]
Nope, don't know that one. Wait for Lari, maybe he will know something more about the release date.

**Pull request merged**
