### PR TITLE
Ensure that toplevel watchedResource path in plugin does not cause StringIndexOutOfBoundsException

### PR DESCRIPTION
**Pull request by andersaaberg**
Candidate fix for: https://github.com/grails/grails-core/issues/10709

### CODE REVIEW

**Comment by brycechasm** [comment]
It's best to describe the change rather than the error message.

**Comment by andersaaberg** [comment]
Good point, I hope that it makes more sense now.

**Comment by andersaaberg** [comment]
I have added a unittest: https://github.com/andersaaberg/grails-core/blob/f958466263cbd422c42059e0d2f350f066f43b0b/grails-core/src/test/groovy/grails/boot/DevelopmentModeWatchSpec.groovy

However, it seems like the buildserver is having trouble with JAVA.

**Comment by graemerocher** [comment]
Please rebase and remove the changes to `.travis.yml` and `.gitattributes`

**Comment by andersaaberg** [comment]
@graemerocher : Done and thanks

**Pull request merged**
