### PR TITLE
#10531 Make TraitInjectors flexible

### PR DESCRIPTION
**Pull request by snimavat**
connect #10531

### CODE REVIEW

**Comment by snimavat** [comment]
@jameskleeh as per your suggestion I added SupportsClassNode, existing trait injectors keep working as it is, if TraitInjector needs to define custom logic, it can implement supports(ClassNode) method

**Comment by snimavat** [comment]
@graemerocher @jameskleeh if you think this feature can be considered but if you have any suggestions for refactoring thn i will make the changes.

**Comment by jameskleeh** [comment]
@snimavat Please update the documentation http://docs.grails.org/latest/guide/plugins.html#addingMethodsAtCompileTime to include this functionality

**Comment by snimavat** [comment]
Sure, i will @jameskeeh

**Comment by snimavat** [comment]
Docs updated https://github.com/grails/grails-doc/pull/558

**Comment by jameskleeh** [comment]
Thanks! merged

**Pull request merged**
