### PR TITLE
Upgrade to version 2.4.2 of maven-clean-plugin for create-pom

### PR DESCRIPTION
**Pull request by armeris**
Fix for issue #10737 in version 2.5.x
(Don't know if it is still supported)

### CODE REVIEW

**Comment by jeffbrown** [comment]
This pull request currently changes versions of some maven related dependencies and also reconfigures our Travis build to use JDK 8 (https://github.com/grails/grails-core/pull/10739/commits/03968e577e1d851683e89434d8a210bc93f6a3c3).  Those are unrelated and should not be lumped together.

**Comment by armeris** [comment]
I changed to JDK 8 because the original oraclejdk7 reported an error in Travis CI.
The error was that the directory for the JDK was not found.
What is the right JDK to set?

**Comment by armeris** [comment]
I've set the JDK version to the original one in .travis.yml but CI is failing. Maybe is an error with the environment.
Here I put some log:

```
$ jdk_switcher use oraclejdk7
Switching to Oracle JDK7 (java-7-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-7-oracle
update-java-alternatives: directory does not exist: /usr/lib/jvm/java-7-oracle
git.checkout
2.58s$ git clone --depth=50 --branch=2.5.x https://github.com/armeris/grails-core.git armeris/grails-core
Cloning into 'armeris/grails-core'...
remote: Counting objects: 6564, done.
remote: Compressing objects: 100% (4566/4566), done.
Receiving objects: 100% (6564/6564), 7.95 MiB | 8.20 MiB/s, done.
remote: Total 6564 (delta 1786), reused 3998 (delta 549), pack-reused 0
Resolving deltas: 100% (1786/1786), done.
$ cd armeris/grails-core
$ git checkout -qf 425d18c8cf8de26f102781ee043d7c7478cd88d9
Setting environment variables from .travis.yml
$ export TERM=dumb
$ export MALLOC_ARENA_MAX=1
$ export GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled"
$ export TERM=dumb
$ java -Xmx32m -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
$ javac -J-Xmx32m -version
javac 1.8.0_131
install
0.02s$ /bin/true
0.04s$ ./gradlew populateDependencies testClasses
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-7-oracle
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

**Comment by armeris** [comment]
It seems that there is a upgrade in the Travis CI server and they have changed the Linux version.
I've set in .travis.yml the the flag `dist: precise` so Travis use the previous version.

**Pull request closed without merging**
