### PR TITLE
fix for issue #9952 and #9953

### PR DESCRIPTION
**Pull request by pjungermann**
The pull request is solving the two issues 9952 and 9953 by skipping interfaces, traits, annotations and inner classes and anonymous classes at the IntegrationTestMixinTransformation.

the branch is based on the tag v2.5.3 (latest 2.5.x release version)

### CODE REVIEW

**Comment by pjungermann** [comment]
@graemerocher : would be great to have it for 2.5.4 also

**Comment by graemerocher** [comment]
Could you please provide a 3.0.x branch pull request too.. thanks

**Comment by pjungermann** [comment]
sure, I'm preparing it. You will have it soon

**Comment by pjungermann** [comment]
PS: as far as I saw there have been quite some changes to that transformation. I will verify if that behaviour still exists in 3.0.11 or if it's gone there. Unfortunately, I used the integration test compiler which does not exist in 3.x anymore. Have to find out how to do it there. If you have any hints.. :)

**Comment by graemerocher** [comment]
@pjungermann Ah yeah, they are quite different, this may not apply to 3.0.x

**Comment by pjungermann** [comment]
as far as I got it, Grails 3 used the annotation `grails.test.mixi.integration.Integration` as marker for those classes which will get transformed. The whole transformation is different too and instead of adding the mixing class which results in a private static final field for the mixing instance, some other annotations get added if it's applicable etc.
I also made a short test and had no issue.

@graemerocher Therefore, I think there is no need for a 3.0.x PR.

**Comment by graemerocher** [comment]
Thanks @pjungermann !

**Comment by pjungermann** [comment]
thanks for merging!

**Pull request merged**
