### PR TITLE
Adding validate to update - 2.5.x

### PR DESCRIPTION
**Pull request by ctoestreich**

### CODE REVIEW

**Comment by ctoestreich** [comment]
@graemerocher  let me know if you want a PR against any other branches for this.

**Comment by graemerocher** [comment]
The issue with this pull request remains the same, but calling `validate()` you are overriding and losing any binding errors:

https://github.com/ctoestreich/grails-core/blob/ecb3dcbab622ff611a6435c25576d6d9982fc5e4/grails-plugin-rest/src/main/groovy/grails/rest/RestfulController.groovy#L150

I don't see why the call to `validate` is needed, because the later call to `save()` will call `validate()`:

https://github.com/ctoestreich/grails-core/blob/ecb3dcbab622ff611a6435c25576d6d9982fc5e4/grails-plugin-rest/src/main/groovy/grails/rest/RestfulController.groovy#L159

**Comment by ctoestreich** [comment]
I am having trouble tracking down the issue this was causing.  It seems under normal circumstances that the save throws the error up to the client in json format just fine for update.

The only issue I am getting with the angular profile is that the update method attempts to render an update.gson that isn't generated with generate-views when using gson-views.  

Without the addition to the `.validate()` then the block of code checking for errors becomes a bit unnecessary as the `hasErrors()` is saying false even if constraints are violated.  What conditions is the [line here](https://github.com/ctoestreich/grails-core/blob/ecb3dcbab622ff611a6435c25576d6d9982fc5e4/grails-plugin-rest/src/main/groovy/grails/rest/RestfulController.groovy#L153) supposed to catch?

**Comment by ctoestreich** [comment]
I will close until I can figure out why I submitted this to begin with.

**Pull request closed without merging**
