### PR TITLE
Fix for issue 9513 - validate() mades private and protected getter methods nullable: false

### PR DESCRIPTION
**Pull request by droggo**
For simple class

```
class NoConstraintsValidateable implements Validateable {
    static constraints = {

    }
}
```

NullPointerException is thrown in validate() method. Provided pull request initializes errors even if constraintsMap is empty + spec

### CODE REVIEW

**Comment by droggo** [comment]
Previous comment is for simple error with empty command object, but please see also related issue -
#9513

**Comment by jeffbrown** [comment]
Can this PR be resubmitted against the `3.0.x` branch?

**Comment by jeffbrown** [comment]
I think this has been superseded by #9528.

Thanks for the help!

**Comment by droggo** [comment]
I'm not sure what you mean by superseded, but #9528 is only for `3.0.x` branch

**Pull request closed without merging**
