### PR TITLE
Introduced EmailValidator and replaced common-validator on EmailConstraint

### PR DESCRIPTION
**Pull request by rpalcolea**
As described in https://github.com/grails/grails-core/issues/10254

This introduces `org.grails.validation.routines.EmailValidator` which relies on `org.grails.validation.routines.DomainValidator` during the validation.

Also replaced `EmailValidator` in `EmailConstraint` to use the new one.

NOTE: I noticed that `org.grails.validation.routines.DomainValidator` doesn't support `allowLocal` so I applied the same approach for the `EmailValidator`.

Tests Results:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.grails.validation.EmailConstraintTests" tests="4" skipped="0" failures="0" errors="0" timestamp="2016-10-20T18:08:55" hostname="Roberto-MacBook-Pro.local" time="0.006">
  <properties/>
  <testcase name="testCreation" classname="org.grails.validation.EmailConstraintTests" time="0.0"/>
  <testcase name="testValidation" classname="org.grails.validation.EmailConstraintTests" time="0.004"/>
  <testcase name="testNullValue" classname="org.grails.validation.EmailConstraintTests" time="0.0"/>
  <testcase name="testBlankString" classname="org.grails.validation.EmailConstraintTests" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>

<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.grails.validation.routines.EmailValidatorTests" tests="12" skipped="0" failures="0" errors="0" timestamp="2016-10-20T18:08:55" hostname="Roberto-MacBook-Pro.local" time="0.006">
  <properties/>
  <testcase name="testEmailWithControlChars" classname="org.grails.validation.routines.EmailValidatorTests" time="0.001"/>
  <testcase name="testEmail" classname="org.grails.validation.routines.EmailValidatorTests" time="0.0"/>
  <testcase name="testEmailWithSlashes" classname="org.grails.validation.routines.EmailValidatorTests" time="0.0"/>
  <testcase name="testEmailExtension" classname="org.grails.validation.routines.EmailValidatorTests" time="0.001"/>
  <testcase name="testEmailWithDash" classname="org.grails.validation.routines.EmailValidatorTests" time="0.0"/>
  <testcase name="testEmailWithCommas" classname="org.grails.validation.routines.EmailValidatorTests" time="0.001"/>
  <testcase name="testEmailWithDotEnd" classname="org.grails.validation.routines.EmailValidatorTests" time="0.0"/>
  <testcase name="testEmailWithSpaces" classname="org.grails.validation.routines.EmailValidatorTests" time="0.0"/>
  <testcase name="testEmailUserName" classname="org.grails.validation.routines.EmailValidatorTests" time="0.002"/>
  <testcase name="testEmailWithBogusCharacter" classname="org.grails.validation.routines.EmailValidatorTests" time="0.0"/>
  <testcase name="testEmailAtTLD" classname="org.grails.validation.routines.EmailValidatorTests" time="0.0"/>
  <testcase name="testEmailWithNumericAddress" classname="org.grails.validation.routines.EmailValidatorTests" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>

```

### CODE REVIEW

**Comment by graemerocher** [comment]
I guess the question is why we need fork EmailValidator if we have upgraded to 1.5.1?

**Comment by rpalcolea** [comment]
Essentially is not needed. I opened this to keep consistence in terms of always use `org.grails.validation.routines.DomainValidator`. 

If you think is better to keep using 1.5.1 is ok :). Keeping Apache Commons up to date will definitely help.

Also, if you decide to use 1.5.1... is it ok if I open a pr to the docs to improve the `email` constraint? I think it would be nice to let developers know that it uses Apache Commons `EmailValidator`

**Comment by graemerocher** [comment]
Sure documentation improvements are always welcome 👍

**Comment by rpalcolea** [comment]
Alright, so I'll close the pr and the issue then, sounds good?

**Comment by graemerocher** [comment]
Sounds good

**Pull request closed without merging**
