### PR TITLE
GRAILS11826 messages.properties translated to Ukrainian (uk)

### PR DESCRIPTION
**Pull request by stokito**
I`ve translated the messages.properties file to Ukrainian (uk).
More than 47 millions of speakers.

### CODE REVIEW

**Comment by jeffbrown** [comment]
Vlad@transferwise.com has agreed to take a look at the translation and provide feedback.

**Comment by Angelys** [comment]
Left some comments to translations.

**Comment by jeffbrown** [comment]
@stokito For Grails 3 this file would be in a different repo.  See https://github.com/grails/grails-profile-repository/tree/master/profiles/base/skeleton/grails-app/i18n.  If you like, incorporate the recommended changes and resubmit the pull request over there.  Since this is a new file that only affects newly created apps, this is a low risk thing and I think we are fine with adding it to 2.5.1 as well.  If you like, make the changes and submit a corresponding pull request to the grails-profile-repository mentioned above and also send a separate pull request here in this repo against the 2.5.x branch instead of the master branch.  In any case, the file will not go in the master branch if this repo as that doesn't make sense so I am going to close this pull request.  Thanks again for your help and once an agreement has been reached on the content we will get this merged.

**Comment by jeffbrown** [comment]
@Angelys Thanks a lot for your help.  We really do appreciate you taking time to help us out.

**Comment by Angelys** [comment]
@jeffbrown If there is anything i can help with just ping me. I would love to contribute.

**Pull request closed without merging**
