### PR TITLE
Fixed a caching bug in GrailsMockHttpServletRequest

### PR DESCRIPTION
**Pull request by MikeThomsen**
Fixed a problem in GrailsMockHttpServletRequest that prevented it from removing stale cached XML and JSON.

### CODE REVIEW

**Comment by jeffbrown** [comment]
@mikert  Is there an Issue that corresponds to this pull request?

**Comment by mikert** [comment]
No, I should probably create one.

**Comment by mikert** [comment]
I just created one. It's https://github.com/grails/grails-core/issues/8996

**Comment by graemerocher** [comment]
Seems to be causing failing tests...

**Comment by mikert** [comment]
Weird part is that the original build errors were on unit tests that showed no signs of using the functionality I changed.

**Pull request merged**
