### PR TITLE
Updating the readme

### PR DESCRIPTION
**Pull request by ctoestreich**
Giving some initial context to these plugins.  Trying help untangle when to use certain gradle plugins and for what reason.

### CODE REVIEW

**Comment by bobbywarner** [comment]
:+1:

**Comment by graemerocher** [comment]
Only thing is the `grails-gsp` subproject is not a Gradle plugin, the gradle plugin is found in `grails-gradle-plugin`

**Comment by bobbywarner** [comment]
@graemerocher Yup, sorry.  I'll update.

**Comment by bobbywarner** [comment]
Fixed here -- https://github.com/grails/grails-core/commit/535d4b5c57d401f12025763ee60061b93982d5e0

**Comment by ctoestreich** [comment]
Ugh... see even I was confused about that. :sos:

**Comment by ctoestreich** [comment]
@graemerocher can you quickly explain the relationship between the grails-gradle-plugin and these projects such as grails-gsp and why the syntax says `apply plugin: "org.grails.grails-web"`  Does the grails-gradle-plugin do something special with the this syntax?

**Comment by ctoestreich** [comment]
These appear more complicated than build scripts...

**Comment by hakanernam** [comment]
+1 about confused. Coming after "apply plugin war", one may be excused for thinking it is a gradle plugin.

**Comment by graemerocher** [comment]
So `org.grails.grails-web` is the id of the Gradle plugin. The Gradle plugins and their ids are defined here:

**Comment by graemerocher** [comment]
Whilst `grails-web` and `grails-gsp` contain the implementations for web related matters and GSP respectively.

Everything related to the Gradle plugin and the Gradle build is in https://github.com/grails/grails-core/tree/master/grails-gradle-plugin

**Comment by ctoestreich** [comment]
This all came about because we noticed that not applying the grails-gsp plugin would cause the project to not process the GSP and other web stuff (which we accidentally removed or used the wrong profile base).  I think I may have incorrectly associated the project with the same name as being the actual gradle plugin.

Are the git projects named grails-web and grails-gsp included independently of their similarly named gradle plugins (which get wired up by the grails-gradle-plugin) or is there a directly relationship between these artifacts and the grails-gradle-plugin?  

Having looked at some of the actual [gradle plugins](https://github.com/grails/grails-core/blob/4001adb3013f5cb372140fb021dad64171070121/grails-gradle-plugin/src/main/groovy/org/grails/gradle/plugin/web/gsp/GroovyPagePlugin.groovy) and the tasks they are exposing, classes they are using etc, it would appear that they simply share a name only and may only be indirectly related.

Sorry for making some cruft around this.  I think what I ultimately want to create/need is a documentation that states what the grails gradle plugin applies actually do.  This is specifically needed for when you start with a project or plugin using a profile that you decide to change the scope of and now need to add additional grails feature support

**Comment by graemerocher** [comment]
No problems. There is no direct relationship between the Gradle plugins and the `grails-web` and `grails-gsp` submodules (which are distinct things)

**Comment by ctoestreich** [comment]
Got it thanks.

**Pull request merged**
