### PR TITLE
Changes for issue #10935

### PR DESCRIPTION
**Pull request by cavemansspa**

### CODE REVIEW

**Comment by graemerocher** [comment]
Please could you update https://github.com/grails/grails-core/blob/master/grails-plugin-mimetypes/src/test/groovy/org/grails/web/servlet/mvc/RequestAndResponseMimeTypesApiSpec.groovy and include a test

**Comment by cavemansspa** [comment]
Added a test for XHR with User-Agent and a non-XHR with User-Agent.

**Comment by graemerocher** [comment]
Thanks for the contribution

**Comment by cavemansspa** [comment]
np, glad i was able to chip in on something.  do we need to make an update in docs?

**Pull request merged**
