### PR TITLE
Fixing configuration loading with Micronaut (issue #11767)

### LINKED ISSUE #11767: Grails 4: property inside plugin has no effect on environment configuration (extension to #11519)
This is an extension to the already closed issue https://github.com/grails/grails-core/issues/11519

The example which I described in my initial issue where a call to `environment.getProperty('grails.databinding.dateFormats')` inside `BootStrap` doesn't return the values from plugin.yml does work now.

But I discovered another use-case where it still doesn't work:
My example of configuring some default framework parameters like `grails.databinding.dateFormats` inside a "core"-plugin still doesn't work. The concrete problem in the databinding case seems to be, that the configuration is now implemented as a Micronaut `@ConfigurationProperties` bean:
```
@ConfigurationProperties("grails.databinding")
public class DataBindingConfigurationProperties {
```

And to me it seems that the configuration from the plugins gets added to the Micronaut context very late:
https://github.com/grails/grails-core/blob/77843bd857d3718d439e264b013eb566fc3afd32/grails-core/src/main/groovy/grails/boot/GrailsApp.groovy#L99-L107

At this point the application context is already created.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create a grails plugin
2. override a default grails property (e.g. grails.databinding.dateFormats) inside the plugin's grails-app/config/plugin.yml file with a non-default value of something like "dd.MM.yyyy"
3. create a grails application
4. add plugin dependency to app
5. try databinding of a "LocalDate" property with a value of "19.03.2021"

### Expected Behaviour

Configuration properties from plugins should be loaded already in the Micronaut context.

### Actual Behaviour

Configuration is loaded when Micronaut context is already setup.

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 4.0.9
- **JDK Version:** 11

### PR DESCRIPTION
**Pull request by davidkron**

### CODE REVIEW

**Comment by davidkron** [comment]
I get the following error from CI:
```
Run scacap/action-surefire-report@v1
Going to parse results form **/build/test-results/test/TEST-*.xml
Result: 1716 tests run, 23 skipped, 0 failed.
Posting status 'completed' with conclusion 'success' to https://github.com/grails/grails-core/pull/11828 (sha: 1c61fb2a855082fd54f408f4df66df4ee2ed4856)
Error: Resource not accessible by integration
```

Can someone support me on what the problem is?

**Comment by puneetbehl** [comment]
@davidkron Thank you for your contribution, I am sorry for the delay. I will take a look in this week itself.

**Comment by jchharris** [comment]
@puneetbehl Is there a plan to incorporate this into a release soon?

**Comment by matrei** [comment]
@puneetbehl I also ran into this issue today. Is there something holding this PR back?

**Comment by matrei** [comment]
@puneetbehl The changes in this PR are not applied to branches 6.0.x and ~~6.1.x~~

**Comment by matrei** [comment]
I am still having issues with #11767.
Example application showing the problem: https://github.com/matrei/mnPluginPropertiesBug

**Pull request merged**
