### PR TITLE
GRAILS-10753 Console Colors in Windows - optional fix

### PR DESCRIPTION
**Pull request by tombujok**
Outputs the ANSI reset sequence and flushes the stream before the System.exit() invocations to make sure that the console has been reset to its default state. 
The potential problem could occur when the out stream has not been fully flushed and the System.exit() invocation finished. 
Last characters of the out stream contain the ANSI reset sequence - if they are not flushed the console keeps the formatting of the previous message.

### CODE REVIEW

**Comment by ikakara** [comment]
FYI - this also happens in grails 3.0.2 and 2.5.0 ... I would be nice to have this fix in both 2.5x and 3x branches.

Thanks!

**Comment by ikakara** [comment]
@tombujok - do you have time to rebase this?

@lhotari - if the fix is based for 2.5.0, will you add it to the 3.x branch?  if tombujok, doesn't have time I can take a crack at rebasing his fix.

**Comment by ikakara** [comment]
@lhotari - I went ahead and took @tombujok changes and applied them into the 2.5.x branch: https://github.com/grails/grails-core/pull/9025 - I would love for these changes to go into the 2.5.1 release.  Let me know if I should merge them into the 3.x branch as well.

Allen

**Comment by graemerocher** [comment]
#9026 was Merged into 2.5.x branch

**Comment by tombujok** [comment]
Sorry, I did not have time to look into it again - thanks for merging!

**Comment by ikakara** [comment]
Sure!  I didn't merge this into the 3.x branch - does the 2.5 branch automagically get merged into the 3.x branch?

**Comment by jeffbrown** [comment]
@ikakara The commit at https://github.com/grails/grails-core/commit/944636f466663c72b68e389f631a6696100f5459 is on the 2.5.x, 3.0.x and master branch.

**Comment by ikakara** [comment]
@jeffbrown - thanks for clarifying.  I need to figure out how github merging/etc works

**Pull request closed without merging**
