### PR TITLE
Added support to exclude build.gradle in profiles skeleton excludes

### PR DESCRIPTION
**Pull request by smakela**
This PR fixes new feature request #11019  that I have requested to be able to use custom build.gradle in your own custom profile. 

Profile's own features can add/merge build.gradle files (and of course profile itself), but not other profiles features or other profiles.

### CODE REVIEW

**Comment by smakela** [comment]
Could someone merge this? Or If this is horrible then it would be nice to even get some comment and I'll make better solution.

**Comment by puneetbehl** [comment]
Sorry for the delayed response. There is less likely to be a next Grails 3.3.x release. If you could please update the change on 4.0.x branch then I will merge this.

**Comment by smakela** [comment]
I'll make this to the 4.0.x branch. I did not have time to make this yet.

**Comment by puneetbehl** [comment]
Sure, thanks!

**Pull request closed without merging**
