### PR TITLE
Fixes issue #11327. JSONTokener should support BigInteger and BigDecimal

### LINKED ISSUE #11327: JSONObject does not support BigInteger and BigDecimal value.
Here is my question from stackoverflow: https://stackoverflow.com/questions/56160624/how-to-handle-post-a-biginteger-in-jsonobject-in-grails-controller

And I find the reason is that `JSONObject` only support number format `Long`, `Integer` and `Double`, without `BigDecimal` and `BigInteger`.

https://github.com/grails/grails-core/blob/de270aedbef5a1af1a11e25554847c0f953682f8/grails-web-common/src/main/groovy/org/grails/web/json/JSONTokener.java#L389-L420

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

see: https://stackoverflow.com/questions/56160624/how-to-handle-post-a-biginteger-in-jsonobject-in-grails-controller

### Expected Behaviour

`JSONObject` could support `BigInteger` and `BigDecimal` value.

### Actual Behaviour

`BigInteger` will be conver to `Double`, and caused arithmetic overflow. 

### Environment Information

- **Operating System**: Linuxmint 19.1
- **Grails Version:** 3.3.6
- **JDK Version:** 1.8
- **Container Version (If Applicable):** TODO

### PR DESCRIPTION
**Pull request by abcfy2**
`JSON.parse('{Json String}')` could support BigInteger and BigDecimal for now.

Like:

```json
{"bigInteger": 9999999999999999999999999999, "bigDecimal": 333.3333333333333333333333333}
```

Fixes #11327

### CODE REVIEW

**Comment by abcfy2** [comment]
Hope this patch could merge to many other supported versions.

**Comment by jeffbrown** [comment]
This pull request has been submitted agains the `master` branch, which only targets Grails 4.  If the intent is for this to be considered for Grails 3, the PR should be sent to the `3.2.x` branch.  Always target the oldest branch that the fix is for and if the change is accepted, we handle merging up to more recent versions from there.

**Comment by jeffbrown** [comment]
Related to #11327

**Comment by abcfy2** [comment]
Thanks. I've created two PRs #11350 #11349 for `3.3.x` and `3.2.x` branch.

**Comment by jameskleeh** [comment]
Duplicated by https://github.com/grails/grails-core/pull/11350

**Comment by abcfy2** [comment]
No, it's not duplicated. Just for different branches.

**Comment by abcfy2** [comment]
Hi @jeffbrown . This pull request is for `master` branch, please merge it.

**Comment by jameskleeh** [comment]
It is duplicated. We merge up so only the 3.2.x one is necessary

**Pull request closed without merging**
