### PR TITLE
2.4.x

### PR DESCRIPTION
**Pull request by vinod2800**
Resolution of GRAILS-11583,
Prob - While using grails webflow, it's adding additional "execution=e1s1"  query string to URL, 

Current Solution - provides configurable parameter to users "grails.views.enable.flowExecutionKey.param" to append query string to url.

Recommended Solution -  remove "urlAttrs.params = params" mapping ( https://github.com/grails/grails-core/blob/v2.4.4/grails-plugin-gsp/src/main/groovy/org/codehaus/groovy/grails/plugins/web/taglib/ApplicationTagLib.groovy#L363) line as it's duplicate place.
grails-web-flow-plugin 2.1.0 - has code to handle execution=e1s1, parameter if you need to bookmark or share the pages.

Thank You,
Vinod

### CODE REVIEW

**Comment by H1net** [comment]
Kind regards,
Ben

--
Ben Newbery
Managing Director
Fresh Devs
Tel.: 0161 408 1009
Mob.: 07769 534 789
Web.: www.freshdevs.com
**Sent from my iPad

**Comment by vinod2800** [comment]
Hi Ben,

I didn't get your comment, or may be forgot to comment, please let me know how to proceed on this change.

Thank You,
Vinod

**Comment by graemerocher** [comment]
The pull request needs to be against the 2.4.x branch not master

**Comment by vinod2800** [comment]
Sorry it's my bad, is there easy way to move to 2.4.x branch

**Comment by kastone** [comment]
Adrien, that work around did not work for us. This pull request has broken all of our sub flows and we really don't want to rely on manually adding the execution parameter in all of our webflow links. Is there anyway to revive the externalized config vinod2800? I think the difference might be sub flows. Are either of you using them? The execution param is necessary in sub flows. You can check out my sample app here: https://github.com/kastone/grails-webflow-sample. If you look at hitAlarmClock.gsp, you will see I tried with the workaround to no avail. Clicking on the links will send user to beginning of webflow b/c the execution param is not included and the state cannot be restored.

**Pull request merged**
