### PR TITLE
Merge test reports of unit and integration tests

### PR DESCRIPTION
**Pull request by nobeans**
Related to: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/grails-dev-discuss/bjtK7M-vRhY/ahVWCf_RuQUJ  and  https://github.com/grails/grails-core/pull/613

### CODE REVIEW

**Comment by nobeans** [comment]
@graemerocher How about this PR?

I've tested as following patterns:

* via Grails-CLI
    * grails clean && grails test-app
        * Unit and integration test reports merged.<-- Improved this!
    * grails clean && grails test-app --unit
        * Only unit test report is there.
    * grails clean && grails test-app --integration
        * Only integration test report is there.
* via Gradle
    * gradle clean check
        * Unit and integration test reports merged. <-- Improved this!
    * gradle clean test
        * Only unit test report is there.
    * gradle clean integrationTest
        * Only integration test report is there.
    * gradle clean test && gradle integrationTest
        * Unit and integration test reports merged. <-- Improved this!

**Comment by graemerocher** [comment]
Thanks!

**Comment by nobeans** [comment]
You're welcome!

**Comment by lhotari** [comment]
Great work @nobeans

**Pull request merged**
